### PR TITLE
IndexedDataset package

### PR DESCRIPTION
**Pull request by zhuyifan1996**
Just a class definition for the data structures. Please merge so that the ML team can start on the same ground.

### CODE REVIEW

**Comment by zhuyifan1996** [comment]
3/3 Finished a first implementation of mini wrappers for IndexedDatasetSpark

**Comment by cfifty** [comment]
Minus the compile error thrown in IntelliJ ("Cannot access scala.Predef.$less$colon$less" for Max xScala = ...), LGTM.  If you can figure out a fix then that'd be preferable since we're primarily working out of IntelliJ.  Otherwise merge into master?

**Comment by jk2227** [comment]
Why is the above error happening? Should investigate before merging

**Comment by cfifty** [comment]
Works w/ sbt compile - seems like an intelliJ specific issue.  I agree with Ji Hun though, we should get it working on intelliJ if possible

**Comment by zhuyifan1996** [comment]
Now this pull request also have the Algorithm.java in engine template. 
Since it also depends on PreparedData, it has pulled changes from the Preparator branch.

**Pull request merged**
